class NIZKPAuthError(Exception):
    ...

class InvalidProfileFormat(NIZKPAuthError):
    ...

class InvalidKeyError(NIZKPAuthError):
    ...

class InvalidUserIDError(NIZKPAuthError):
    ...
    
class InvalidCurveError(NIZKPAuthError):
    ...

class InvalidHashError(NIZKPAuthError):
    ...

class InvalidHashCurveCombinationError(NIZKPAuthError):
    ...
