class NIZKPAuthError(Exception):
    ...

class InvalidProfileFormat(NIZKPAuthError):
    ...

class InvalidKeyError(NIZKPAuthError):
    ...

class InvalidUserIDError(NIZKPAuthError):
    ...
    
class InvalidCurveError(NIZKPAuthError):
    ...

class InvalidCurveName(InvalidCurveError):
    ...

class InvalidHashError(NIZKPAuthError):
    ...

class InvalidHashName(InvalidHashError):
    ...

class InvalidHashCurveCombinationError(NIZKPAuthError):
    ...

class InvalidProofFormat(NIZKPAuthError):
    ...